### ISSUE TITLE
`/about` page founder-section content needs moved to Netlify CMS

### ISSUE THREAD

**Issue by appleJax** [san-diego-tech-hub/sdth-site#128]
Right now the `/about` page Founder's section content is hard coded into the React component. It needs to come from Netlify CMS instead.

![Screen Shot 2019-04-12 at 10 02 21 PM](https://user-images.githubusercontent.com/13618860/56074909-cab29e00-5d6e-11e9-8280-78a0f50a8d05.png)

**Comment by funkaj** [comment]
Almost done, sorry for the delay.

**Comment by appleJax** [comment]
Fixed by #142
