### ISSUE TITLE
Add a "Register a Venue" card and form on the Get Involved page

### ISSUE THREAD

**Issue by jonathandavidlewis** [san-diego-tech-hub/sdth-site#148]
We need a way for individuals to register a venue for use in the "places" option of the Network page.

This is so that the Network: Places search results have a bank of registered places from which to query.

- [ ] Add a new card to the get-involved page:
  https://www.sandiegotechhub.com/get-involved
  ![image](https://user-images.githubusercontent.com/23508546/60760266-71fa4680-9fe7-11e9-81ff-1f98b9b027a6.png)
  - [ ] Text should read: "Register a Venue"
  - [ ] Suggestion for graphic on the card, tech hub logo:
    ![image](https://user-images.githubusercontent.com/23508546/60760288-f0ef7f00-9fe7-11e9-9d58-9a58ba142541.png)
  - [ ] Card should have a "SEE DETAILS" link with more info about hosting.
- [ ] Add a Google form to register a Venue
  - [ ] Example form: https://docs.google.com/forms/d/e/1FAIpQLSfHKVp-GtcXrXoY-qA5X9FWS6ssU9wNspDkI-OxUQvA3GdrOA/viewform (To be updated with actual link)

The Google form should have the following fields to fill:
- Name
- Name of venue
- Description
- Capacity
- Cost
- Address
- Amenities from a list
- Image url
(anything else...)

**Comment by jonathandavidlewis** [comment]
@appleJax Any chance you could get a form created and update the ticket to reflect the actual link to embed?

**Comment by appleJax** [comment]
Done

<img width="431" alt="Screen Shot 2019-07-20 at 11 09 29 AM" src="https://user-images.githubusercontent.com/13618860/61582380-f74d2300-aade-11e9-86e8-aee7dc73906e.png">
