### ISSUE TITLE
Add "Sign up for the newsletter"

### ISSUE THREAD

**Issue by jonathandavidlewis** [san-diego-tech-hub/sdth-site#163]
Add "Sign up for the newsletter" in smaller text below "get involved"

On the bottom of the home page, we ask for user info to "Stay connected" but we do not inform them what the info is for.

![image](https://user-images.githubusercontent.com/23508546/62416498-bd0c7700-b5f0-11e9-920e-a25e0613cd9b.png)

**Comment by appleJax** [comment]
Fixed by #165
