### ISSUE TITLE
Get Involved Button has css issue involving colors

### ISSUE THREAD

**Issue by Rockleeland** [san-diego-tech-hub/sdth-site#184]
**Describe the bug**
The "Get Involved" button on the right side has #2abbf4 color on the bottom which is inconsistent with the styling of the button in all other pages.

**To Reproduce**
1. Go to 'https://www.sandiegotechhub.com/get-involved'
2. Observe the 'Get Involved' button on the right side
4. See the #2abbf4 color on the button

**Expected behavior**
The button should only be #629d04

**Screenshots**
![sdth-button](https://user-images.githubusercontent.com/31978878/66862220-55a26a00-ef45-11e9-98f4-39178c8ce0d6.PNG)

**System Info (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browser: Chrome

**Comment by appleJax** [comment]
The blue underline is supposed to signify that you are currently on the `/get-involved` page.
