### ISSUE TITLE
Please add our October sponsor logo

### ISSUE THREAD

**Issue by tiszavolgyi** [san-diego-tech-hub/sdth-site#185]
Can you have the logo of our October sponsor below added to https://www.sandiegotechhub.com/partners

and link to https://arkusnexus.com/

Thank you!

![Arkusnexus](https://user-images.githubusercontent.com/19597726/67440339-d4368180-f5ad-11e9-9fa5-696350146d4a.png)

**Comment by appleJax** [comment]
Fixed by #186

**Comment by tiszavolgyi** [comment]
@appleJax @huynhicode - Could we please put the most recent sponsor to the top of the list? The new sponsor should be the first, so we give the new ones the visibility and opus down the older sponsors. 
It also looks a bit smaller than the other ones.
Thank you both!

**Comment by huynhicode** [comment]
Yes, done.  Also, Arkus Nexus logo is the same size as the others now.  Will submit PR.

<img width="979" alt="Screen Shot 2019-10-24 at 12 42 57 PM" src="https://user-images.githubusercontent.com/35910788/67519506-d7884680-f65b-11e9-8e00-96efd1ce97b7.png">

**Comment by appleJax** [comment]
Fixed by #187
