### ISSUE TITLE
Another Sponsor logo

### ISSUE THREAD

**Issue by tiszavolgyi** [san-diego-tech-hub/sdth-site#189]
Hi,

Could you please also add the attached logo to the site. It is Nick's company, which was sponsoring one of the events in the past. **Please add it after Seamgen and before Qimia.** 

![FL_Logo](https://user-images.githubusercontent.com/19597726/67598359-30221700-f722-11e9-90ce-cf13e59d7b51.jpg)

Thank you!

**Comment by huynhicode** [comment]
Yes, done.  

<img width="965" alt="Screen Shot 2019-10-25 at 1 34 50 PM" src="https://user-images.githubusercontent.com/35910788/67602926-8ac07080-f72c-11e9-85c1-11183cb02dcf.png">

**Comment by appleJax** [comment]
Fixed by #188
