### ISSUE TITLE
Add the attached logo to the partner area

### ISSUE THREAD

**Issue by tiszavolgyi** [san-diego-tech-hub/sdth-site#195]
Please add the attached logo to the partner section. The link should point to here: https://www.fwscience.com/ 

Thank you!

![Framework_Science_Logo_Com_2018](https://user-images.githubusercontent.com/19597726/68251406-e1089b80-ffd7-11e9-8621-6c71dfab0665.png)

**Comment by appleJax** [comment]
Done

**Comment by tiszavolgyi** [comment]
Sorry Kevin, it supposed to go to the Sponsors, they will be the next food sponsor. My bad, sorry for the double work...

**Comment by appleJax** [comment]
👍
