### ISSUE TITLE
Add automatic prettier-formatting when committing files?

### ISSUE THREAD

**Issue by jhuynh85** [san-diego-tech-hub/sdth-site#45]
Hey all, I spoke to Kevin about this, but since we're using Prettier for code formatting, would anyone be against the idea of having a pre-commit hook to automatically have Prettier format files before they're committed to the repo? It would go a long way in maintaining consistent formatting throughout the codebase.

I was thinking of going with **Option 1** referenced [here](https://prettier.io/docs/en/precommit.html).

**Comment by appleJax** [comment]
@jhuynh85 I like it! We should also get ESLint set up while we're at it. Do you wanna take this one on?

I have a project with the following ESLint config that works pretty well:

## Packages:
- eslint-config-airbnb
- eslint-plugin-import
- eslint-plugin-jsx-a11y
- eslint-plugin-react

Here's a good starting point for the `eslint.rc.js` (we can customize it as we see fit):
```
module.exports = {
  'extends': 'airbnb',
  'plugins': [
      'react',
      'jsx-a11y',
      'import'
  ],
  'rules': {
      'semi': 0,
      'comma-dangle': 0,
      'global-require': 0,
      'react/prop-types': 0,
      'import/no-unresolved': 0,
      'import/no-webpack-loader-syntax': 0,
      'jsx-a11y/click-events-have-key-events': 0,
      'react/no-danger': 0,
      'no-multi-spaces': 0,
      'jsx-a11y/anchor-has-content': 0,
      'jsx-a11y/label-has-for': 0,
      'jsx-a11y/no-static-element-interactions': 0,
      'arrow-body-style': 0,
      'react/forbid-prop-types': 0,
      'react/require-default-props': 0,
      'camelcase': 0,
      'no-console': 0,
      'import/prefer-default-export': 0,
      'linebreak-style': 0,
      'jsx-a11y/anchor-is-valid': 0,
      'react/no-unescaped-entities': 0,
      'react/jsx-closing-tag-location': 0,
      'react/jsx-filename-extension': 0,
      'function-paren-newline': 0,
      'react/jsx-one-expression-per-line': 0,
      'react/jsx-first-prop-new-line': 0,
      'react/jsx-indent-props': 0,
      'import/no-extraneous-dependencies': 0,
      'object-curly-newline': 0,
      'no-restricted-globals': 0,
      'arrow-parens': 0,
      'import/no-useless-path-segments': 0,
      'import/no-cycle': 0,
  },
  'parser': 'babel-eslint',
  'globals': {
      'location': 1,
      'alert': 1,
      'fetch': 1,
      'graphql': 1,
      'document': 1,
      'localStorage': 1,
      'window': 1,
      'navigator': 1,
      'Notification': 1,
      'FormData': 1,
      '__PATH_PREFIX__': 1
  }
};
```

**Comment by jhuynh85** [comment]
@appleJax Almost done setting this up, do you want to automatically run `eslint --fix` on staged files as well or just have it display the errors?

**Comment by appleJax** [comment]
@jhuynh85 awesome! Let's have it display errors for now. That way we can adjust the rules as we go.
