### ISSUE TITLE
All buttons should have hover states

### ISSUE THREAD

**Issue by appleJax** [san-diego-tech-hub/sdth-site#65]
It would be nice for all clickable items on the website to have the following styles on hover:
- `cursor: pointer`
- some subtle color change

**Comment by appleJax** [comment]
@funkaj if you look at the hover state of buttons on GitHub, it's a nice subtle touch to darken the button border on hover.

**Comment by funkaj** [comment]
@appleJax Thanks, took your advice and darkened the borders.

**Comment by appleJax** [comment]
Fixed by #83
