### ISSUE TITLE
Sponsor logos should link to the sponsor website

### ISSUE THREAD

**Issue by appleJax** [san-diego-tech-hub/sdth-site#78]
On the partners page, the Partner Organization logos link to their respective websites. The Sponsor Organizations currently do not, but they should. Also, we should make more discoverable the fact that the logos are clickable.

![Screen Shot 2019-03-14 at 1 43 31 PM](https://user-images.githubusercontent.com/13618860/54390268-4d0c4d00-465f-11e9-8936-f6d0bb615688.png)

**Comment by funkaj** [comment]
I have corrected the discover-ability of the sponsorship links in issue 65 button hover fix.

**Comment by funkaj** [comment]
Also the links appear to be working already.

**Comment by appleJax** [comment]
Thanks @funkaj 🙌
