### ISSUE TITLE
React Toast font needs to be bigger

### ISSUE THREAD

**Issue by appleJax** [san-diego-tech-hub/sdth-site#90]
Currently the font is a little hard to read on the `react-toastify` notifications.

![Screen Shot 2019-03-19 at 2 55 27 PM](https://user-images.githubusercontent.com/13618860/54716620-5b50e200-4b13-11e9-8f2b-768bb00ff017.png)

**Comment by jhuynh85** [comment]
`react-toastify` documentation: https://github.com/fkhadra/react-toastify#api

**Comment by tiszavolgyi** [comment]
All the forms have email validation, how can you reproduce this / see this toast?

**Comment by appleJax** [comment]
@tiszavolgyi you can fill out the Stay Connected form with the following values:
- Name: `test`
- Email: `test@test.com`

Those values will pass validation, but the newsletter subscription will fail, and you'll see an error toast.
