### ISSUE TITLE
We Need a Code of Conduct for the Website and the Repo

### ISSUE THREAD

**Issue by appleJax** [san-diego-tech-hub/sdth-site#93]
We should add a code of conduct to the website footer. Also, we should have a code of conduct for this repository.

**Comment by jhuynh85** [comment]
For reference, github has a template here: https://github.com/san-diego-tech-hub/sdth-site/community/code-of-conduct/new?template=citizen-code-of-conduct

**Comment by appleJax** [comment]
Fixed by #95
